#!/usr/bin/env bash
# Re-run DBA experiments for CIFAR10 with visualizations: alpha=0.1, 500 epochs, 4 adv
# Defenses: CPLRFL, Mean, TrimmedMean, RFA -- all on GPU 1
#
# Visualizations are generated by main.py into the run log directory:
#   - noniid_*_distribution.png
#   - dba_triggers_*.png
#   - *_convergence.png

cd "$(dirname "$0")/.."

# 1. CPLRFL
nohup python main.py --config configs/FedAvg_CIFAR10_config.yaml \
  -e 500 -dtb non-iid -dirichlet_alpha 0.1 -att DBA -def CPLRFL -gidx 1 \
  -defense_params '{"samples_per_class":50,"similarity_metric":"mmd","tau":1.0,"mmd_kernel":"rbf","mmd_gamma":null}' \
  > nohup_DBA_CIFAR10_CPLRFL_500ep_alpha01.out 2>&1 &

# 2. Mean
nohup python main.py --config configs/FedAvg_CIFAR10_config.yaml \
  -e 500 -dtb non-iid -dirichlet_alpha 0.1 -att DBA -def Mean -gidx 1 \
  > nohup_DBA_CIFAR10_Mean_500ep_alpha01.out 2>&1 &

# 3. TrimmedMean
nohup python main.py --config configs/FedAvg_CIFAR10_config.yaml \
  -e 500 -dtb non-iid -dirichlet_alpha 0.1 -att DBA -def TrimmedMean -gidx 1 \
  > nohup_DBA_CIFAR10_TrimmedMean_500ep_alpha01.out 2>&1 &

# 4. RFA
nohup python main.py --config configs/FedAvg_CIFAR10_config.yaml \
  -e 500 -dtb non-iid -dirichlet_alpha 0.1 -att DBA -def RFA -gidx 1 \
  > nohup_DBA_CIFAR10_RFA_500ep_alpha01.out 2>&1 &
