#!/usr/bin/env bash
# Re-run DBA experiments with visualizations: alpha=0.05, 500 epochs, 4 adv
# Defenses: CPLRFL, Mean, TrimmedMean, RFA -- all on GPU 1
#
# Visualizations auto-generated by main.py into the log directory:
#   - noniid_alpha0.05_distribution.png  (non-IID label distribution)
#   - dba_triggers.png                   (original + local/global triggers)
#   - *_convergence.png                  (Train Loss, Test Loss, Test Acc, ASR)
#
# Copy-paste each command individually, or run this script.

cd "$(dirname "$0")/.."

# 1. CPLRFL
nohup python main.py --config configs/FedAvg_MNIST_config.yaml \
  -e 500 -dtb non-iid -dirichlet_alpha 0.05 -att DBA -def CPLRFL -gidx 1 \
  -defense_params '{"samples_per_class":50,"similarity_metric":"mmd","tau":1.0,"mmd_kernel":"rbf","mmd_gamma":null}' \
  > nohup_DBA_CPLRFL_500ep_alpha005.out 2>&1 &

# 2. Mean
nohup python main.py --config configs/FedAvg_MNIST_config.yaml \
  -e 500 -dtb non-iid -dirichlet_alpha 0.05 -att DBA -def Mean -gidx 1 \
  > nohup_DBA_Mean_500ep_alpha005.out 2>&1 &

# 3. TrimmedMean
nohup python main.py --config configs/FedAvg_MNIST_config.yaml \
  -e 500 -dtb non-iid -dirichlet_alpha 0.05 -att DBA -def TrimmedMean -gidx 1 \
  > nohup_DBA_TrimmedMean_500ep_alpha005.out 2>&1 &

# 4. RFA
nohup python main.py --config configs/FedAvg_MNIST_config.yaml \
  -e 500 -dtb non-iid -dirichlet_alpha 0.05 -att DBA -def RFA -gidx 1 \
  > nohup_DBA_RFA_500ep_alpha005.out 2>&1 &
